---
abstract: 'Build Your Application Instance Programatically'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.2.0, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CatalystX-AppBuilder
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  CatalystX::AppBuilder:
    file: lib/CatalystX/AppBuilder.pm
    version: '0.00010'
requires:
  Catalyst: '5.80024'
  Moose: '0'
  namespace::clean: '0'
resources:
  bugtracker: https://github.com/lestrrat/CatalystX-AppBuilder/issues
  homepage: https://github.com/lestrrat/CatalystX-AppBuilder
  repository: git://github.com/lestrrat/CatalystX-AppBuilder.git
version: '0.00010'
x_contributors:
  - 'Colin Newell <colin@opusvl.com>'
  - 'Colin Newell <colin.newell@gmail.com>'
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
